### ISSUE TITLE
Update Price Ranges via JSON API

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/meredith-core#12]
https://www.figma.com/file/d1s8SvSRxoMMDz2QOu5BQeE2/Untitled?node-id=0%3A1

We have 8-9 properties with different prices per day. Need a way to drop this data into postgres without having to manually add thousands of rows (high chance for error).

Because the cms is not fully designed yet, look/feel can be pure html/no styling. Just need to start working on the function to interact with the database. 

https://docs.google.com/spreadsheets/d/1nK15V2k0vu6Nyvt7pxbKeL5hlyItwaHsIScQzmeRmFI/edit?usp=sharing

**Comment by StrangeWill** [comment]
This will require auth before we roll to production or anyone could insert prices, so I guess I'll task that out in a little bit.

**Comment by kavleenSabharwal** [comment]
> https://www.figma.com/file/d1s8SvSRxoMMDz2QOu5BQeE2/Untitled?node-id=0%3A1
> 
> We have 8-9 properties with different prices per day. Need a way to drop this data into postgres without having to manually add thousands of rows (high chance for error).
> 
> Because the cms is not fully designed yet, look/feel can be pure html/no styling. Just need to start working on the function to interact with the database.
> 
> https://docs.google.com/spreadsheets/d/1I5hJXS6TcN6dz57rXlx5NVejMmp1x28VZP1RvoMdJgo/edit?usp=sharing

HI
Just checked it out, I guess its easy to drop this data on Postgre, 
I did't understand what kind of functions do you want to have in the cms. I mean what kind of interactions. 
If you select the date should all types of housing options be available to you along with the price?
I'm guessing the choice can be for - date, price range 
I can't think of anything else, let me know if I am going in the right direction

**Comment by paulchrisluke** [comment]
You are correct. @atharva3010 is building a calendar function. If you check out airbnb, you can select the range of dates in a calendar (ui), and then enter the price for those dates (applies that price to the range of days).

**Comment by kavleenSabharwal** [comment]
> You are correct. @atharva3010 is building a calendar function. If you check out airbnb, you can select the range of dates in a calendar (ui), and then enter the price for those dates (applies that price to the range of days).

@atharva3010 I will need to see the cms before designing function to connect db. I have imported the sheet on Postgres, and will be ready with the database with respect to the function soon

**Comment by StrangeWill** [comment]
@kavleenSabharwal the database and the models already exist here:

Price listing:
https://github.com/whynotearth/meredith-core/blob/release/0.3.0/WhyNotEarth.Meredith.App/Controllers/Api/v0/HotelController.cs#L24

Price model:
https://github.com/whynotearth/meredith-core/blob/release/0.3.0/WhyNotEarth.Meredith.Data.Entity/Models/Modules/Hotel/Price.cs

Ideally: we need a new pricing controller (since we're not doing CRUD against a pricing object) that can read/write individual pricing records for the CMS.

Generally our CMS design is headless, we should never depend on the Vue application to drive any API design, because a headless design assumes no control over external applications reading/writing data, it just creates a standard for creating/updating/serving data.

From that point, we may build some kind of utility that leverages the API to dump that sheet in -- not exactly sure where that responsibility is going to lie, since the sheet is a one-off it may just be a script someone whips up to import.

**Comment by StrangeWill** [comment]
Update for the above links: pricing got moved to a per-room type basis, so expect the listing to be per room type.

**Comment by SoksanSerey** [comment]
@StrangeWill I want to work with that issue. Can you guy me how to do so? I'm still new to C# and Asp.net

**Comment by SoksanSerey** [comment]
@StrangeWill 
When I try to run the project it showed me the error message `Couldn't find a project to run. Ensure a project exists in D:\Development\DGK\meredith-core, or pass the path to the project using --project.
`

1. First I try to run `dotnet restore` and `dotnet build` one more time and start to run project by `dotnet run`, it still produce the error
2. Then I try to follow this [link](https://stackoverflow.com/questions/50048591/couldnt-find-a-project-to-run-ensure-a-project-exists-in-d-home-site-wwwroot) from stackower flow and nothing gonna work
3. I also try to follow this [link](https://github.com/dotnet/docfx/issues/1497), it ain't work either
Can you lead me the way to solve this issue.
![Annotation 2019-08-09 085426](https://user-images.githubusercontent.com/29726037/62749076-43a7d500-ba85-11e9-85c2-0342c668b17b.png)

**Comment by StrangeWill** [comment]
You need to do that from within a project folder, not the solution folder, try `WhyNotEarth.Meredith.App`.

It's probably best you fire up docker too.

Also you need to copy `appsettings.json` to `appsettings.local.json` and configure it to use the docker container for the database.
