### ISSUE TITLE
add multi language support 

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/meredith-core#20]
So for proper multilingual support, tables start to look like this

![image](https://user-images.githubusercontent.com/5694308/71759730-e012be00-2ee3-11ea-8a1a-b05f55cfa72b.png)

Amenities, Beds, Hotels, Rules, Spaces all get translation tables.
And each have one row per language
Prices may change too

**Comment by paulchrisluke** [comment]
I think @mort3za has finished most of his work here, just needs an endpoint? How much work is that @StrangeWill ? If we write that out, I'm pretty sure I may be able to find a junior person to work on this... getting lots of our backend stuff more organized and docummented to go for more contributors.

**Comment by paulchrisluke** [comment]
What experience level would we need to get that done if you are not the one
doing it? Seems like a good first contributor issue? I just wouldn’t know
how to write it. Julia is getting good at writing and tasking front end
tasks now though... as an aside , is there a format or template we can
follow to make requests better?

**Comment by StrangeWill** [comment]
It's simple enough that if you know what you're doing, the work is pretty trivial, just time consuming because we're adding it after the fact. I think the difficulty is we've had a lot of people slide in that couldn't do even easier tasks...

Julia could cruise the tables and call out everything that needs to get pulled out into a Language table.

**Comment by paulchrisluke** [comment]
@SimonRask , possible good one for you

**Comment by paulchrisluke** [comment]
@StrangeWill ready for review.
