### ISSUE TITLE
Newly created tenant's have slugs with space in them

### ISSUE THREAD

**Issue by atharva3010** [whynotearth/meredith-core#216]
Below is an example of a newly created tenant created using `/api/v0/companies/{companySlug}/tenants`
```
{
"slug":"atharva sharma",
"name":"Atharva Sharma",
"logo":null,
"tags":[],
"deliveryTime":"00:00:00",
"deliveryFee":0.0
}
```
You can see the complete tenant list here https://stagingapi.whynot.earth/api/v0/companies/foodouken/tenants

**Comment by pjanicked** [comment]
@atharva3010 @paulchrisluke does it need to have extra validations like removing/detecting special characters or such? or removing space is enough

**Comment by atharva3010** [comment]
@pjanicked I am not sure about that, @ctyar or @StrangeWill can answer better. 

Slugs are created at the server side automatically and not passed from the client side.

**Comment by StrangeWill** [comment]
Yeah so a few things (this applies to company slugs which we never added a slugify command to this project for):

- Slugs should be unique, due to being on postgres 9 case insensitivity is a pain in the butt, consider moving to postgres 12 so you can use case insensitive collations.
  - ToLowering on slug lookups destroy indexes and therefore performance
  - You can ToLower indexes but this requires a syntax that I don't think is available to EF Core without just writing indexes by hand
  - You'll need to resolve slug uniqueness issues if you're just generating off of the name (a guess based on this data though)

https://www.nuget.org/packages/Slugify.Core/ may be good for handling the slugs for us, it's not complex code but they got tests so...
