### ISSUE TITLE
shift reservation endpoint to support saved cart for users.

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/meredith-core#265]
/api/v0/tenants/{tenantSlug}/reservations

We are wanting to save order info to a profile so users do not need to log in or enter their personal details every time. Need a couple shifts to support this on the frontend:

"it would be a one to many realationship where you need three columns in a new db table. One column for tenantslug_id and user_id keys then a cartdata column to store json of cart

every addition / removal of a product in cart would need an API call

so the way I made it makes it so that if a tenant changes their slug

then the cart saved data will still work

"

```
{
  "cart": [
    {
      "name": "cheese",
      "count": 2,
      "price": 2.00
    },
    {
      "name": "bread",
      "count": 1,
      "price": 2.00
    }
  ],
  slug: "ankor-taco",
  "subTotal": 6.00,
  "amount": 6.00,
  "tax": 0,
}
```

**Comment by StrangeWill** [comment]
Since we're saving the entire cart as a JSON blob instead of persisting it as a relational cart these side effects can happen:

- The Vue store is now dependent on adhering to the structure in the database, this includes not breaking carts on upgrades, how do we want process updates in the JSON structure?
- If I change product prices/taxes/etc. how is this reflected in the store when it's loaded?
- Do we re-validate prices prior to submission to prevent tampering?
- Ideally slugs should only get used for customer-facing pages (eg: urls) IDs should be used for internal storage (eg: a slug change doesn't break all carts)

**Comment by paulchrisluke** [comment]
- The Vue store is now dependent on adhering to the structure in the database, this includes not breaking carts on upgrades, how do we want process updates in the JSON structure?

We don’t have an issue with sticking to a fixed json structure, frontend chews whatever backend throws.

- If I change product prices/taxes/etc. how is this reflected in the store when it's loaded?  

Yea, we would need a periodic price check... but unlikely we will run into this problem for the current usage rate.

- Do we re-validate prices prior to submission to prevent tampering?


If each cart addition is an api call Frontend gets simplified. Since all the heavy lifting is being done on the back, we would just display the data so we don’t need to revalidate. If there are errors we can display that to the user.

If the cart is managed by backend we can simply display the data.

- Ideally slugs should only get used for customer-facing pages (eg: urls) IDs should be used for internal storage (eg: a slug change doesn't break all carts)

yes..?! I think it should be all pass by id/slug


Cc: @atharva3010  for all these great answers

**Comment by paulchrisluke** [comment]
@pjanicked has made progress here, need to submit pr and review. look at adding testing

![image](https://user-images.githubusercontent.com/5694308/91530815-f15a8000-e935-11ea-869f-46b97eba8255.png)
