### ISSUE TITLE
Extra fields required to be sent along with reservation

### ISSUE THREAD

**Issue by atharva3010** [whynotearth/meredith-core#39]
We need these fields to be sent along with the roomTypeID and dates, to reserve the property, they should also be visible at a glance, when pulled via the get reservation info endpoint.

- Name
- E-mail
- Phone number
- Check in
- Check out (different than dateTwo)
- Bed type (count and Type)
- Transportation needed
- Message
- Property name
- No. Of guests

**Comment by StrangeWill** [comment]
> Transportation needed

This is part of add-ons so may see about adding that sooner rather than later...


> - Name
> - E-mail
> - Phone number
> - Check in
> - Message

Easy ones

> - Check out (different than dateTwo)

We're going to expect the check-out date, not the ending price date passed us. This will be up to the Vue app.

> - Bed type (count and Type)
> - Property name

These are implied from the reservation structure

> - Transportation needed

This is going to have to be part of #34

**Comment by StrangeWill** [comment]
Added everything but transportation, which is part of #34.
