### ISSUE TITLE
Implement email notifications for reservation process

### ISSUE THREAD

**Issue by ctyar** [whynotearth/meredith-core#74]
https://github.com/whynotearth/hotel-website-vkirirom.com/issues/386

**Comment by vishnu2848** [comment]
I want to contribute to this project. I did my 6 months intern in .net development. Can u please explain me the project and the issues, so i can work in this project.

**Comment by paulchrisluke** [comment]
Welcome @vishnu2848 , great to hear you found out about this project! We have a `[discord ](https://discord.gg/V3Ja2b)`we chat on, but I can give you a brief rundown:

Meredith-core is a rest api that builds hotel websites like https://vkirirom.com . She builds the web pages, manages functions like calendar booking, stripe transactions, and user authentication. In this issue, we are looking to move the email functions to the backend, since our current implementation is kinda hacky (front end). 

We use Sendgrid for our email process, which has a pretty good [api and documentation
](https://sendgrid.com/docs/for-developers/sending-email/v3-csharp-code-example/).

We need to use Sengrid to send thank you confirmation emails for bookings made in our reservation system. We can help guide you along depending on experience, discord would probably be best for a short intro and hash out the best way to document this task for you!

**Comment by vishnu2848** [comment]
Actually I worked on integration with the Freshdesk and Salesforce in my six months intern. I can use the Sendgrid to send the emails as it has the API. I didn't check the Sendgrid APIs Yet.

**Comment by vishnu2848** [comment]
When I tried to open the discord link you sent above, it is showing as an invalid URL. Can we discuss it here itself?

**Comment by paulchrisluke** [comment]
Yes! Right now, when a user makes a reservation we call a request to a little express server and use sendgrid's api to send a thank you email.

We use endgrids dynamic emails
```
<html lang="en">
  <body style="font-family: sans-serif; color: #191C21;">
    <img style="max-width: 100%;" src="{{resort.featuredImage}}" />
    <h2>{{resort.h2}}</h2>
    <p>{{numberOfGuests}} Guests</p>
    <p>{{checkIn}} <span>&#11208;</span> {{checkOut}}</p>

    <hr />
    <p>{{nightsCount}} nights total</p>
    {{#each prices}}
    <div><small>{{this.date}} - ${{this.amount}}</small></div>
    {{/each}}
    <p>VAT 10% - ${{vat}}</p>
    <hr />

    <h3>Total - ${{amount}}</h3>
    <h3>Customer Details</h3>
    <div>
      <p>Customer name: {{name}}</p>
      <p>Country: {{phoneCountry}}</p>
      <p>Phone Number: {{phone}}</p>
      <p>Email: {{email}}</p>
    </div>
    
    {{#if message}}
    <h3>Special Requirements</h3>
    <p>{{message}}</p>
    {{/if}}
    
    <hr />

    
    <h1>Thank You!</h1>
    <p>
      Thank you for selecting vKirirom Resort as your preferred resort. Your payment has been processed successfully.
    </p>
    <h2>vKirirom Pine Resort</h2>
    <p>Preah Soramarith-Kosamak National Park (Kirirom), Phnom Srouch District, Kompong Speu Province, Cambodia</p>
    <p><a href="https://goo.gl/maps/PqV15Qcq9dSSJcso9">Get Directions</a></p>
    <p><a href="tel:+(855) 78 777 284">+(855) 78 777 284</a></p>
    <p><a href="mailto:info@vkirirom.com">info@vkirirom.com</a></p>
    <h3>Need Transportation?</h3>
    <p>
      vKirirom Pine Resort offers a easy shuttle service for visitors between Kirirom and Phnom Penh. Click to reserve
      your shuttle now.
    </p>
    <a href="http://shuttlebus.vkirirom.com/login">Sign Up Now</a>
    
    <h3>Room Description</h3>
    {{{roomDescriptionHTML}}}
  </body>
</html>
```
Instead of calling our unsecure express server, we want to move this functionality to Meredith-core. @ctyar and @StrangeWill are both backend devs on this project, and good resources for questions. I'll try another discord link, because we use it like Slack and a good place to learn and get quicker responses:

https://discord.gg/5T7D33c

**Comment by ctyar** [comment]
I think the first step would be sending just a sample email.
There are a few libraries in NuGet to work with SendGrid.
We need to choose the best one.
The end result would be a service that gets basic information for an email and communicates with SendGrid with the help of the library we chose.

This is our current implementation in js in case you need it.
https://github.com/whynotearth/netlify-express/blob/master/express/utils/sendgrid.js

Let me know if you have any questions or need anything else.

**Comment by paulchrisluke** [comment]
@ctyar be sure to design this in a way that works with all clients as an email system from meredith-core... our next client we onboard will be a Hair Salon booking app, which will be sending thank you emails as well, want to build the meredith-core section of communications in a way that is not specific to vkirirom.


 @atharva3010 has some experience in this area. Perhaps we can go over it in the #engineering channel today .
